version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netshield
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/netshield
      SECRET_KEY: change_this_to_a_long_random_string
    ports:
      - "8000:8000"
    volumes:
      - ../ml:/app/../ml

  frontend:
    build: ../frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
